"""
QR Scanner — NammaPark RPi Camera Module (Pi Camera Module)

Uses picamera2 (libcamera stack, Raspberry Pi OS Bullseye+) to capture
frames from the official Pi Camera Module V2, and OpenCV's QRCodeDetector
to decode QR codes from those frames.

When a valid QR is detected:
  1. The raw text is parsed as JSON and validated against the NammaPark schema.
  2. A cooldown check prevents duplicate publishes of the same QR.
  3. An entry_scan MQTT event is published — the backend validates the
     booking_token and responds with a gate_command to open the servo.

QR Payload Schema (generated by Android app, validated here):
  {
    "booking_id": <int>,
    "token":      "<secrets.token_hex(8)>",
    "plot_id":    <int>,
    "vehicle":    "<vehicle_number>",
    "issued_at":  "<ISO8601>"
  }

MQTT Topics Published:
  parking/plot/{plot_id}/entry_scan
    Payload: { "booking_token": "<raw_qr_json_str>", "timestamp": "<ISO8601>" }

Dependencies (install on Pi):
  sudo apt install -y python3-picamera2       # Pi Camera V2 driver
  pip install opencv-python-headless          # QR decoding (no GUI)

Pi Camera setup:
  - Enable camera interface:  sudo raspi-config → Interface Options → Camera
  - Verify:                   libcamera-hello  (should show preview)
  - picamera2 uses the libcamera stack; do NOT use legacy 'raspistill' mode.
"""

import json
import logging
import threading
import time
from datetime import datetime, timezone
from typing import Callable, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Try to import picamera2 (Pi Camera driver)
# ---------------------------------------------------------------------------
try:
    from picamera2 import Picamera2  # type: ignore
    _PICAMERA2_AVAILABLE = True
    logger.info("picamera2 loaded — Pi Camera Module ready")
except ImportError:
    _PICAMERA2_AVAILABLE = False
    Picamera2 = None  # type: ignore
    logger.warning(
        "picamera2 not found — QR scanner will run in SIMULATION mode. "
        "Install on Pi: sudo apt install -y python3-picamera2"
    )

# ---------------------------------------------------------------------------
# Try to import OpenCV (QR decoder)
# ---------------------------------------------------------------------------
try:
    import cv2  # type: ignore
    _CV2_AVAILABLE = True
    logger.info("OpenCV loaded — QR decoding ready")
except ImportError:
    _CV2_AVAILABLE = False
    cv2 = None  # type: ignore
    logger.warning(
        "opencv-python-headless not installed — QR decoding unavailable. "
        "Install with: pip install opencv-python-headless"
    )

# Simulation mode if either dependency is missing
_SIMULATION_MODE = not (_PICAMERA2_AVAILABLE and _CV2_AVAILABLE)


# ---------------------------------------------------------------------------
# QR Payload Validation
# ---------------------------------------------------------------------------

REQUIRED_QR_FIELDS = {"booking_id", "token", "plot_id", "vehicle", "issued_at"}


def parse_qr_payload(raw_text: str) -> Optional[dict]:
    """
    Decode and validate a raw QR text string.

    Expected format: compact JSON matching the NammaPark QR schema.

    Args:
        raw_text: The raw string decoded from the QR image

    Returns:
        Parsed dict if valid, None if invalid/malformed
    """
    try:
        data = json.loads(raw_text.strip())
    except (json.JSONDecodeError, ValueError):
        logger.warning("QR payload is not valid JSON: %s", raw_text[:100])
        return None

    missing = REQUIRED_QR_FIELDS - set(data.keys())
    if missing:
        logger.warning("QR payload missing required fields %s: %s", missing, data)
        return None

    # Type checks
    if not isinstance(data.get("booking_id"), int):
        logger.warning("QR 'booking_id' must be int, got: %s", type(data.get("booking_id")))
        return None
    if not isinstance(data.get("token"), str) or not data["token"]:
        logger.warning("QR 'token' must be a non-empty string")
        return None
    if not isinstance(data.get("plot_id"), int):
        logger.warning("QR 'plot_id' must be int, got: %s", type(data.get("plot_id")))
        return None

    return data


# ---------------------------------------------------------------------------
# QR Scanner
# ---------------------------------------------------------------------------

class QRScanner:
    """
    Background camera loop that captures frames from the Pi Camera Module,
    decodes QR codes, and publishes MQTT entry_scan events.

    Frame capture:  picamera2  (libcamera — works with Pi Camera Module V2)
    QR decoding:    cv2.QRCodeDetector

    Flow per frame:
      1. picamera2 captures an RGB888 array
      2. Convert RGB → BGR for OpenCV
      3. cv2.QRCodeDetector.detectAndDecode()
      4. Validate JSON payload + plot_id
      5. Cooldown check (dedup)
      6. Publish parking/plot/{id}/entry_scan

    Usage:
        scanner = QRScanner(
            plot_id=1,
            publish_fn=mqtt_client.publish,
            scan_interval=0.5,
            cooldown_seconds=10,
            camera_width=640,
            camera_height=480,
        )
        scanner.start()
        # ... runs in background ...
        scanner.stop()
    """

    def __init__(
        self,
        plot_id: int,
        publish_fn: Callable[[str, str, int], bool],
        camera_index: int = 0,        # kept for API compatibility; picamera2 ignores this
        scan_interval: float = 0.5,
        cooldown_seconds: int = 10,
        camera_width: int = 640,
        camera_height: int = 480,
    ):
        """
        Initialise the QR scanner.

        Args:
            plot_id:          The plot ID this RPi manages (used in MQTT topics)
            publish_fn:       MQTT publish function — (topic, payload, qos) -> bool
            camera_index:     Unused for picamera2; kept for API compatibility
            scan_interval:    Seconds between frame captures (0.5 = 2 fps)
            cooldown_seconds: Seconds to ignore repeat scans of the same QR token
            camera_width:     Capture frame width in pixels
            camera_height:    Capture frame height in pixels
        """
        self._plot_id       = plot_id
        self._publish_fn    = publish_fn
        self._scan_interval = scan_interval
        self._cooldown_secs = cooldown_seconds
        self._cam_width     = camera_width
        self._cam_height    = camera_height
        self._simulation    = _SIMULATION_MODE

        # Cooldown tracking: raw_qr_text → monotonic timestamp of last publish
        self._cooldown_map: dict[str, float] = {}
        self._cooldown_lock = threading.Lock()

        # Thread control
        self._running    = False
        self._stop_event = threading.Event()
        self._thread: Optional[threading.Thread] = None

        logger.info(
            "QRScanner initialised: plot=%d, resolution=%dx%d, interval=%.1fs, "
            "cooldown=%ds, sim=%s",
            plot_id, camera_width, camera_height,
            scan_interval, cooldown_seconds, self._simulation,
        )

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self) -> None:
        """Start the background QR scanning thread."""
        if self._running:
            logger.warning("QRScanner already running")
            return

        self._running = True
        self._stop_event.clear()
        self._thread = threading.Thread(
            target=self._scan_loop,
            name="qr-scanner",
            daemon=True,
        )
        self._thread.start()
        logger.info("QR scanner started")

    def stop(self) -> None:
        """Stop the background scanning thread gracefully."""
        if not self._running:
            return
        self._running = False
        self._stop_event.set()
        if self._thread:
            self._thread.join(timeout=5)
        logger.info("QR scanner stopped")

    # ------------------------------------------------------------------
    # Main scanning loop
    # ------------------------------------------------------------------

    def _scan_loop(self) -> None:
        """Background thread: open Pi Camera, scan frames until stopped."""
        if self._simulation:
            logger.info(
                "[SIM] QR scanner loop running — no camera attached. "
                "Use inject_test_qr() to simulate a scan."
            )
            while not self._stop_event.wait(timeout=1.0):
                pass
            return

        # --- Initialise picamera2 ---
        picam2 = self._open_picamera()
        if picam2 is None:
            logger.error("Failed to open Pi Camera — QR scanning aborted")
            return

        detector = cv2.QRCodeDetector()
        logger.info(
            "Pi Camera started (%dx%d) — scanning for QR codes",
            self._cam_width, self._cam_height,
        )

        try:
            while not self._stop_event.is_set():
                # Capture latest frame as numpy array (RGB888)
                frame_rgb = picam2.capture_array()

                # Convert RGB → BGR for OpenCV
                frame_bgr = cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2BGR)

                # Attempt QR decode
                raw_text, points, _ = detector.detectAndDecode(frame_bgr)

                if raw_text:
                    self._handle_raw_scan(raw_text.strip())

                # Throttle capture rate
                self._stop_event.wait(timeout=self._scan_interval)

        except Exception as exc:
            logger.error("Unexpected error in QR scan loop: %s", exc, exc_info=True)
        finally:
            picam2.stop()
            picam2.close()
            logger.info("Pi Camera released")

    def _open_picamera(self) -> Optional["Picamera2"]:
        """
        Initialise and start picamera2 with a still-capture configuration.

        Using create_still_configuration() gives better image quality for
        QR decoding compared to the preview stream.  The main stream is set
        to RGB888 so frames are directly usable by OpenCV after a colour swap.

        Returns:
            Running Picamera2 instance, or None on failure.
        """
        try:
            picam2 = Picamera2()

            config = picam2.create_still_configuration(
                main={
                    "size":   (self._cam_width, self._cam_height),
                    "format": "RGB888",   # numpy array → H×W×3 uint8 RGB
                }
            )
            picam2.configure(config)
            picam2.start()

            # Warm-up: let auto-exposure settle
            time.sleep(0.3)

            logger.info(
                "Pi Camera opened: %dx%d (RGB888, still config)",
                self._cam_width, self._cam_height,
            )
            return picam2

        except Exception as exc:
            logger.error("Error opening Pi Camera via picamera2: %s", exc, exc_info=True)
            return None

    # ------------------------------------------------------------------
    # QR handling
    # ------------------------------------------------------------------

    def _handle_raw_scan(self, raw_text: str) -> None:
        """
        Process a decoded QR string:
          1. Cooldown check
          2. JSON parse + schema validation
          3. plot_id validation
          4. Publish entry_scan via MQTT
          5. Update cooldown
        """
        # Cooldown dedup
        if self._is_on_cooldown(raw_text):
            logger.debug("QR on cooldown — ignoring: %.40s…", raw_text)
            return

        logger.info("QR detected: %.120s", raw_text)

        # Parse + validate payload
        payload = parse_qr_payload(raw_text)
        if payload is None:
            logger.warning("QR payload invalid — discarding")
            return

        # Validate plot_id matches this device
        qr_plot_id = payload.get("plot_id")
        if qr_plot_id != self._plot_id:
            logger.warning(
                "QR plot_id=%s does not match this device's plot_id=%d — discarding",
                qr_plot_id, self._plot_id,
            )
            return

        # Build MQTT payload
        # Per roadmap §2.5: always publish to entry_scan;
        # backend decides check-in vs check-out from booking state.
        topic = f"parking/plot/{self._plot_id}/entry_scan"
        mqtt_payload = json.dumps({
            "booking_token": raw_text,    # full raw JSON (backend re-parses)
            "timestamp":     datetime.now(timezone.utc).isoformat(),
        })

        success = self._publish_fn(topic, mqtt_payload, 1)

        if success:
            logger.info(
                "QR scan published → %s | booking_id=%s, vehicle=%s",
                topic, payload.get("booking_id"), payload.get("vehicle"),
            )
            self._set_cooldown(raw_text)
        else:
            logger.warning(
                "Failed to publish QR scan event — MQTT may be disconnected; "
                "will retry on next scan"
            )

    # ------------------------------------------------------------------
    # Cooldown helpers
    # ------------------------------------------------------------------

    def _is_on_cooldown(self, raw_text: str) -> bool:
        with self._cooldown_lock:
            last = self._cooldown_map.get(raw_text)
            return last is not None and (time.monotonic() - last) < self._cooldown_secs

    def _set_cooldown(self, raw_text: str) -> None:
        now = time.monotonic()
        with self._cooldown_lock:
            self._cooldown_map[raw_text] = now
            # Prune stale entries
            self._cooldown_map = {
                k: v for k, v in self._cooldown_map.items()
                if (now - v) < self._cooldown_secs
            }

    # ------------------------------------------------------------------
    # Testing / Simulation helpers
    # ------------------------------------------------------------------

    def inject_test_qr(self, raw_qr_text: str) -> None:
        """
        Manually inject a QR scan event — bypasses the camera entirely.

        Useful for development on non-Pi machines and for integration tests.

        Args:
            raw_qr_text: QR text string (compact JSON per NammaPark schema)
        """
        logger.info("[TEST] Injecting QR scan: %.120s", raw_qr_text)
        self._handle_raw_scan(raw_qr_text)

    @property
    def is_running(self) -> bool:
        """True if the scanning thread is active."""
        return self._running

    @property
    def is_simulation(self) -> bool:
        """True when running without real Pi Camera / OpenCV."""
        return self._simulation
